// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beczyzooflivhbmjiomb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlY3p5em9vZmxpdmhibWppb21iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzc1NTgsImV4cCI6MjA2MDgxMzU1OH0.SQe-ANqSCa8jHwPD5MdRl8iZ9BcvNGoZvuiNH0CxdAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);